### PR TITLE
Feat: Digital Public Goods page added

### PR DESCRIPTION
**Pull request by 0-mayurkaretha**
Describe:
Added UI for the Digital Public Goods page, reference issue: [#3](https://github.com/Code4GovTech/website/issues/3) 

Achieved Goals:

- [x] Design and develop the Digital Public Goods page layout
- [x] Add relevant content to the Digital Public Goods page
- [x] Make it responsive
- [x] Implement Cypress tests for the Digital Public Goods page

### CODE REVIEW

**Comment by 0-mayurkaretha** [comment]
Succeed deployment [here](https://website-gpwp6xjm2-samagra.vercel.app/DigitalPublicGoods), (../DigitalPublicGoods)

-The issue with not passing the checks of vercel deployment that to install `react-animate-on-scroll` package it uses simply `npm install ` which requires `--force` to install because of the version difference.

-Just wanted to mention that I have tried overriding vercel default installation command `npm install` changing to `npm install --force` which worked smoothly [here](https://mayur-temp-public-goods-f6cp.vercel.app/DigitalPublicGoods).

I removed the package and to overcome this will add alternative of it.

**Comment by Shruti3004** [comment]
hey @0-mayurkaretha, currently the site is not responsive and are not having test-cases as well

**Comment by 0-mayurkaretha** [comment]
Hello @Shruti3004 ma'am, I've added Cypress tests and responsive design, please review it once.

> c4gt.webm
> 
> Hey @0-mayurkaretha, currently the site is not responsive and are not having test-cases as well

**Comment by Shruti3004** [comment]
Hey @0-mayurkaretha possible to quickly connect on your PR?

**Comment by 0-mayurkaretha** [comment]
Sure, we can connect on discord.

> Hey @0-mayurkaretha possible to quickly connect on your PR?

**Comment by Shruti3004** [comment]
## Action items from the call

- Replace the hex code rgba(23,37,84,.95) and use `bg-primary-color` class
- Remove the double quotes " from the text
- Remove the navbar and footer ans use the same header and footer
- Vertically aligned the DPG text in the box
- Fix the responsiveness

**Comment by Shruti3004** [comment]
Hey @0-mayurkaretha can you please fix the merge conflicts?

**Comment by 0-mayurkaretha** [comment]
conflicts resolved here [`c3f0e64`](https://github.com/Code4GovTech/website/pull/12/commits/c3f0e6448c425f07a2bd852c8a0c051ada1348cd).

> Hey @0-mayurkaretha can you please fix the merge conflicts?

**Review by Shruti3004 — APPROVED** [review]

**Comment by Shruti3004** [comment]
Thanks @0-mayurkaretha

**Pull request merged**
